---
title: "Practical Computational Biology: R"
author: "Sujatha Jagannathan"
date: "February 24, 2020"
output: ioslides_presentation
incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Learning objectives for this course
> The primary learning objectives are to work towards being able to:  

* Retrieve and import genomic data.  
* Prepare data for analysis (“tidy”-ing).  
* Conduct basic exploratory analysis - getting familiar with your dataset.  
* Test specific hypotheses using computational methods.  
* Visualize and communicate your results.  
* Practice reproducible analysis.  

## Today's class outline

- Coding best practices
- Review data types
- In-class exercise on RNAseq dataset
    + Import
    + Explore
    + Tidy
    + Export
- Homework instructions

## Class rules {.build .bigger}

- Ask for help (use the stickie notes)  

- Offer help!   
      + We have a wide range of R experience in this class room  
      + Pair with someone with a different R expertise and help each other  

- Use Google *liberally*  (& the cheatsheets!)